### ISSUE TITLE
Task "run" fails

### ISSUE THREAD

**Issue by Unic8** [davidB/gradle-getdown-plugin#21]
What I expected:

That my mainclass of the application I wrote will be started using the mainclass I setup.

But it fails with following error:

    gradlew.bat run
    :run
    Fehler: Hauptklasse path.to.my.mainclass konnte nicht gefunden oder geladen werden // <== Could not find or load mainclass
    :run FAILED

    FAILURE: Build failed with an exception.

    * What went wrong:
    Execution failed for task ':run'.
            > Process 'command 'C:\Program Files\Java\jdk1.7.0_60\bin\java.exe'' finished with non-zero exit value 1

    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

            BUILD FAILED

    Total time: 3.342 secs

**Comment by davidB** [comment]
I replace the 'run' task by 'launch' task (that depends of bundle_0) and run getdownApp.
less issue, allow to test digest and remove conflict with plugin 'application' (both can be used)
